<?php

function getBrowser() 
{ 
    $u_agent = $_SERVER['HTTP_USER_AGENT']; 
    $bname = 'Unknown';
    $platform = 'Unknown';
    $version= "";

    //First get the platform?
    if (preg_match('/linux/i', $u_agent)) {
        $platform = 'linux';
    }
    elseif (preg_match('/macintosh|mac os x/i', $u_agent)) {
        $platform = 'mac';
    }
    elseif (preg_match('/windows|win32/i', $u_agent)) {
        $platform = 'windows';
    }

    // Next get the name of the useragent yes seperately and for good reason
    if(preg_match('/MSIE/i',$u_agent) && !preg_match('/Opera/i',$u_agent)) 
    { 
        $bname = 'Internet Explorer'; 
        $ub = "MSIE"; 
    } 
    elseif(preg_match('/Firefox/i',$u_agent)) 
    { 
        $bname = 'Mozilla Firefox'; 
        $ub = "Firefox"; 
    } 
    elseif(preg_match('/Chrome/i',$u_agent)) 
    { 
        $bname = 'Google Chrome'; 
        $ub = "Chrome"; 
    } 
    elseif(preg_match('/Safari/i',$u_agent)) 
    { 
        $bname = 'Apple Safari'; 
        $ub = "Safari"; 
    } 
    elseif(preg_match('/Opera/i',$u_agent)) 
    { 
        $bname = 'Opera'; 
        $ub = "Opera"; 
    } 
    elseif(preg_match('/Netscape/i',$u_agent)) 
    { 
        $bname = 'Netscape'; 
        $ub = "Netscape"; 
    } 

    // finally get the correct version number
    $known = array('Version', $ub, 'other');
    $pattern = '#(?<browser>' . join('|', $known) .
    ')[/ ]+(?<version>[0-9.|a-zA-Z.]*)#';
    if (!preg_match_all($pattern, $u_agent, $matches)) {
        // we have no matching number just continue
    }

    // see how many we have
    $i = count($matches['browser']);
    if ($i != 1) {
        //we will have two since we are not using 'other' argument yet
        //see if version is before or after the name
        if (strripos($u_agent,"Version") < strripos($u_agent,$ub)){
            $version= $matches['version'][0];
        }
        else {
            $version= $matches['version'][1];
        }
    }
    else {
        $version= $matches['version'][0];
    }

    // check if we have a number
    if ($version==null || $version=="") {$version="?";}

    return array(
        'userAgent' => $u_agent,
        'name'      => $bname,
        'version'   => $version,
        'platform'  => $platform,
        'pattern'    => $pattern
    );
} 

$ua=getBrowser();

$contentarray = array('<q>Aren&apos;t you just <b>bored</b> with all those slides-based presentations?</q>',
                      '<q>Don&apos;t you think that presentations given <strong>in modern browsers</strong> shouldn&apos;t <strong>copy thelimits</strong> of &apos;classic&apos; slide decks?</q>',
                      '<q>Would you like to <strong>impress your audience</strong> with <strong>stunning visualization</strong> ofyour talk?</q>',
                      '<span class="try">then you should try</span><h1>impress.js<sup>*</sup></h1><span class="footnote"><sup>*</sup> no rhyme intended</span>',
                      '<p>It&apos;s a <strong>presentation tool</strong> <br/>inspired by the idea behind <a href="http://prezi.com">prezi.com</a> <br/>and based on the <strong>power of CSS3 transforms and transitions</strong> in modern browsers.</p>',
                      '<p>visualize your <b>big</b> <span class="thoughts">thoughts</span></p>',
                      '<p>and <b>tiny</b> ideas</p>',
                      '<p>by <b class="positioning">positioning</b>, <b class="rotating">rotating</b> and <b class="scaling">scaling</b> them on an infinite canvas</p>',
                      '<p>the only <b>limit</b> is your <b class="imagination">imagination</b></p>',
                      '<p>want to know more?</p><q><a href="http://github.com/bartaz/impress.js">use the source</a>, Luke!</q>',
                      '<p>one more thing...</p>',
                      '<p><span class="have">have</span> <span class="you">you</span> <span class="noticed">noticed</span> <span class="its">it&apos;s</span> <span class="in">in</span> <b>3D<sup>*</sup></b>?</p><span class="footnote">* beat that, prezi ;)</span>',
                      '<p>and now, you can load the presentation as json-data</p>',
                      '',
                      '<q>This demo impress.js presentation is generated by php from an array to a json-file.</q><p>To confirm this, the following list contains data of your connection:</p><ul><li>IP-Adress: '.$_SERVER["REMOTE_ADDR"].'</li><li>Request time: '.$_SERVER["REQUEST_TIME"].'</li><li>Browser: '.$ua['name'].'</li><li>OS: '.$ua['platform'].'</li></ul>');

$json = json_encode(array("language" => "en",
                          "title" => "impress.js | presentation tool based on the power of CSS3 transforms and transitions in modern browsers | by Bartek Szopka @bartaz",
                          "description" => "impress.js is a presentation tool based on the power of CSS3 transforms and transitions in modern browsers and inspired by the idea behind prezi.com.",
                          "author" => "Bartek Szopka",
                          "css" => array("http://fonts.googleapis.com/css?family=Open+Sans:regular,semibold,italic,italicsemibold|PT+Sans:400,700,400italic,700italic|PT+Serif:400,700,400italic,700italic", "./css/impress-demo.css"),
                          "favicon" => "http://bartaz.github.com/impress.js/favicon.png",
                          "touchicon" => "http://bartaz.github.com/impress.js/apple-touch-icon.png",
                          "slides" => array(array("id" => "generated",      "class" => "step slide",    "position" => array("x" => -2000, "y" => -1500),                             "rotate" => array(rand(70,120)),           "content" => $contentarray[14]),
                                            array("id" => "bored",          "class" => "step slide",    "position" => array("x" => -1000, "y" => -1500),                             "rotate" => array(rand(70,120)),           "content" => $contentarray[0]),
                                            array("id" => "",               "class" => "step slide",    "position" => array("x" => 0,     "y" => -1500),                             "rotate" => array(rand(70,120)),           "content" => $contentarray[1]),
                                            array("id" => "",               "class" => "step slide",    "position" => array("x" => 1000,  "y" => -1500),                             "rotate" => array(rand(70,120)),           "content" => $contentarray[2]),
                                            array("id" => "title",          "class" => "step",          "position" => array("x" => 0,     "y" => 0),                  "scale" => 4,                                             "content" => $contentarray[3]),
                                            array("id" => "its",            "class" => "step",          "position" => array("x" => 850,   "y" => 3000),               "scale" => 5,  "rotate" => array(90),                     "content" => $contentarray[4]),
                                            array("id" => "big",            "class" => "step",          "position" => array("x" => 3500,  "y" => 2100),               "scale" => 6,  "rotate" => array(180),                    "content" => $contentarray[5]),
                                            array("id" => "tiny",           "class" => "step",          "position" => array("x" => 2825,  "y" => 2325, "z" => -3000), "scale" => 1,  "rotate" => array(rand(270,330)),          "content" => $contentarray[6]),
                                            array("id" => "ing",            "class" => "step",          "position" => array("x" => 3500,  "y" => -850),               "scale" => 6,  "rotate" => array(270),                    "content" => $contentarray[7]),
                                            array("id" => "imagination",    "class" => "step",          "position" => array("x" => 6700,  "y" => -300),               "scale" => 6,                                             "content" => $contentarray[8]),
                                            array("id" => "source",         "class" => "step",          "position" => array("x" => 6300,  "y" => 2000),               "scale" => 4,  "rotate" => array(rand(5,35)),             "content" => $contentarray[9]),
                                            array("id" => "one-more-thing", "class" => "step",          "position" => array("x" => 6000,  "y" => 4000),               "scale" => 2,                                             "content" => $contentarray[10]),
                                            array("id" => "its-in-3d",      "class" => "step",          "position" => array("x" => 6200,  "y" => 4300, "z" => -100),  "scale" => 2,  "rotate" => array("x" => -40, "y" => 10),  "content" => $contentarray[11]),
                                            array("id" => "json",           "class" => "step",          "position" => array("x" => 4000,  "y" => 4300, "z" => -120),  "scale" => 2,  "rotate" => array("x" => -140, "y" => 10), "content" => $contentarray[12]),
                                            array("id" => "overview",       "class" => "step",          "position" => array("x" => 3000,  "y" => 1500),               "scale" => 10,                                            "content" => $contentarray[13])
                                            )));

if(substr($_SERVER["REQUEST_URI"], -17) == 'original.json.php')
  {
    echo $json;
  }

?>